version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: bskit
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    dir: .
    main: .
    binary: bskit
    hooks:
      pre:
        - rm -rf build/bin
        - rm -rf frontend/.next
        - wails build -platform {{ .Os }}/{{ .Arch }}

archives:
  - id: bskit
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - build/bin/bskit.app/Contents/MacOS/bskit

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: titan-syndicate
    name: bskit
  prerelease: auto
