name: Wails release

on:
  release:
    types: [published]

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'bskit'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'bskit'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'bskit'
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.22'

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/bin/*
          token: ${{ secrets.GITHUB_TOKEN }}